### PR TITLE
Uncertainty profiler

### PR DESCRIPTION
**Pull request by xwa9860**
The git history is clear of .pdf, .eps, .serr, .sub, .log files.
Let me know what I can do next.

### CODE REVIEW

**Comment by katyhuff** [comment]
Hm, it looks like there are now almost twice as many eps and pdf files as there were before.

See the comparison:
https://github.com/pyrk/pyrk/pull/9/files

**Comment by xwa9860** [comment]
Now, all pdf and eps files should be removed, for real.

**Comment by katyhuff** [comment]
Can you merge the master branch into your uncertainty-profiler branch and deal with the conflicts? Without that, unfortunately, the continuous integration system can't run the tests on travis. If that's too confusing, I can get to it later tonight.

**Comment by xwa9860** [comment]
I will not be able to start before tonight. Send me an email when you start
working on this, I will do the same, so we don't repeat.



On Wed, Aug 5, 2015 at 11:17 AM, Katy Huff <notifications@github.com> wrote:

> Can you merge the master branch into your uncertainty-profiler branch and
> deal with the conflicts? Without that, unfortunately, the continuous
> integration system can't run the tests on travis. If that's too confusing,
> I can get to it later tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/9#issuecomment-128096793>.
>



-- 
-----------------------------------------
Xin WANG | 王昕
PhD Student
Thermal Hydraulics Laboratory
Nuclear Engineering Department
University of California, Berkeley
(415)408-1691

**Comment by katyhuff** [comment]
Take your time. It doesn't have to be done tonight. I was just offering to look at it if you felt the merge was too confusing/tricky. If you're willing to handle it, that would be great, but there's no deadline. Thanks!

**Comment by xwa9860** [comment]
I merge the master branch to uncertainty-profiler. But some tests failed, most of them failed because of  units.

**Comment by katyhuff** [comment]
I had hoped you would be making a pull request only for the changes related
to fvm. Is there no way to separate those commits from the ones related to
units and submit a pr just for those, as we discussed in our meeting?

**Comment by xwa9860** [comment]
I did put the units back in input file, and I used the original
density-model file during this merge.
I understood that we want two separate branches for FVM changes and for
units changes. But I didn't separate the changes for units in a different
branch.  Would there be a way to separate now, if I tell you which commit
numbers they are?


On Thu, Aug 6, 2015 at 8:08 AM, Katy Huff <notifications@github.com> wrote:

> I had hoped you would be making a pull request only for the changes related
> to fvm. Is there no way to separate those commits from the ones related to
> units and submit a pr just for those, as we discussed in our meeting?
>
> On Wed, Aug 5, 2015, 10:55 PM Xin Wang <notifications@github.com> wrote:
>
> > I merge the master branch to uncertainty-profiler. But some tests failed,
> > most of them failed because of units.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pyrk/pyrk/pull/9#issuecomment-128254659>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/9#issuecomment-128405967>.
>



-- 
-----------------------------------------
Xin WANG | 王昕
PhD Student
Thermal Hydraulics Laboratory
Nuclear Engineering Department
University of California, Berkeley
(415)408-1691

**Comment by katyhuff** [comment]
You can use git cherry-pick . This will only really work if none of the
commits include changes both for fvm and for units.




On Thu, Aug 6, 2015 at 9:46 AM, Xin Wang <notifications@github.com> wrote:

> I did put the units back in input file, and I used the original
> density-model file during this merge.
> I understood that we want two separate branches for FVM changes and for
> units changes. But I didn't separate the changes for units in a different
> branch. Would there be a way to separate now, if I tell you which commit
> numbers they are?
>
>
> On Thu, Aug 6, 2015 at 8:08 AM, Katy Huff <notifications@github.com>
> wrote:
>
> > I had hoped you would be making a pull request only for the changes
> related
> > to fvm. Is there no way to separate those commits from the ones related
> to
> > units and submit a pr just for those, as we discussed in our meeting?
> >
> > On Wed, Aug 5, 2015, 10:55 PM Xin Wang <notifications@github.com> wrote:
> >
> > > I merge the master branch to uncertainty-profiler. But some tests
> failed,
> > > most of them failed because of units.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pyrk/pyrk/pull/9#issuecomment-128254659>.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pyrk/pyrk/pull/9#issuecomment-128405967>.
> >
>
>
>
> --
> -----------------------------------------
> Xin WANG | 王昕
> PhD Student
> Thermal Hydraulics Laboratory
> Nuclear Engineering Department
> University of California, Berkeley
> (415)408-1691
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/9#issuecomment-128436918>.
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
closing because the tests aren't passing. Please reopen when completely reviewable.

**Pull request closed without merging**
