### PR TITLE
Database

### PR DESCRIPTION
**Pull request by katyhuff**
This adds a first pass at an HDF5 database. Things that are not perfect include simhashing and the neutronics data table. However, this is ready to be tested.

### CODE REVIEW

**Comment by xwa9860** [comment]
Is the new database branch ready for review and merge?

**Comment by katyhuff** [comment]
Yes! That would be great. You can always review a PR when it's there waiting and the tests are passing. This current PR is the db branch. Note that it doesn't include  the db_faster branch. The faster branch can be reviewed and merged separately after I add another couple of tests. It's best to keep them small an separate in any case.


Thanks!!

**Comment by xwa9860** [comment]
Cool, im going to merge it. I am finalizing the multi-point branch.

On Thu, Dec 10, 2015 at 4:01 PM, Katy Huff <notifications@github.com> wrote:

> Yes! That would be great. You can always review a PR when it's there
> waiting and the tests are passing. This current PR is the db branch. Note
> that it doesn't include the db_faster branch. The faster branch can be
> reviewed and merged separately after I add another couple of tests. It's
> best to keep them small an separate in any case.
>
> Thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/25#issuecomment-163748025>.
>



-- 
-----------------------------------------
Xin WANG | 王昕
PhD Student
Thermal Hydraulics Laboratory
Nuclear Engineering Department
University of California, Berkeley
(415)408-1691

**Comment by katyhuff** [comment]
Did you review it at all? I'd be happy to have responded to any review
comments if you had them.

On Thu, Dec 10, 2015 at 1:08 PM, Xin Wang <notifications@github.com> wrote:

> Merged #25 <https://github.com/pyrk/pyrk/pull/25>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/25#event-488676726>.
>



-- 
http://katyhuff.github.com

**Comment by xwa9860** [comment]
haha yes, kind of. I don't have any constructive comments because I've never done anything like this, so just made sure that I understand what you were doing.

**Comment by katyhuff** [comment]
Ok. Thanks,
Katy

On Thu, Dec 10, 2015 at 1:16 PM, Xin Wang <notifications@github.com> wrote:

> haha yes, kind of. I don't have any constructive comments because I've
> never done anything like this, so just made sure that I understand what you
> were doing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyrk/pyrk/pull/25#issuecomment-163751518>.
>



-- 
http://katyhuff.github.com

**Pull request merged**
