### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by ElijahCapps**
Updated some of the documentation within the doc directory (added edits from issue #88, fixed typos, etc.).

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks -- for future reference, you want to assign people if you need them to contribute code. You'll want to name folks as "Reviewers" if you want them to review. I'm switching myself from assignee to reviewer on this PR.

**Review by katyhuff — CHANGES_REQUESTED** [review]
Nice work, thanks! 

Minor grammatical suggestions included below (accept or reject these changes through the github interface). 

One issue : I think there have been a number of folks who have problems running pyrk because, instead of installing it and running it from outside the pyrk directory, they run it from inside the pyrk directory.  Should we make a note of that somewhere in the tutorial doc?

**Comment by ElijahCapps** [comment]
Committed suggested changes, modified line lengths, and added clarification about running setup.py first, and the location of driver.py. Please let me know if this is what you had in mind.

**Comment by katyhuff** [comment]
Excellent work!

**Pull request merged**
